let employees = [
  {
    id: 1,
    firstName: "Arjun",
    email: "employee1@example.com",
    password: "1234",
    tasks: [
      {
        title: "Task 1 for Arjun",
        description: "Description of Task 1",
        date: "2024-11-21",
        priority: "High",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2 for Arjun",
        description: "Description of Task 2",
        date: "2024-11-22",
        priority: "Medium",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3 for Arjun",
        description: "Description of Task 3",
        date: "2024-11-23",
        priority: "Low",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4 for Arjun",
        description: "Description of Task 4",
        date: "2024-11-24",
        priority: "High",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5 for Arjun",
        description: "Description of Task 5",
        date: "2024-11-25",
        priority: "Medium",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 6 for Arjun",
        description: "Description of Task 6",
        date: "2024-11-26",
        priority: "Low",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 7 for Arjun",
        description: "Description of Task 7",
        date: "2024-11-27",
        priority: "High",
        category: "Development",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 8 for Arjun",
        description: "Description of Task 8",
        date: "2024-11-28",
        priority: "Medium",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 6,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Aarav",
    email: "employee2@example.com",
    password: "1234",
    tasks: [
      {
        title: "Task 1 for Aarav",
        description: "Description of Task 1",
        date: "2024-11-21",
        priority: "Medium",
        category: "Operations",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2 for Aarav",
        description: "Description of Task 2",
        date: "2024-11-22",
        priority: "Low",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3 for Aarav",
        description: "Description of Task 3",
        date: "2024-11-23",
        priority: "High",
        category: "Operations",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4 for Aarav",
        description: "Description of Task 4",
        date: "2024-11-24",
        priority: "Medium",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5 for Aarav",
        description: "Description of Task 5",
        date: "2024-11-25",
        priority: "Low",
        category: "Operations",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 6 for Aarav",
        description: "Description of Task 6",
        date: "2024-11-26",
        priority: "High",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 7 for Aarav",
        description: "Description of Task 7",
        date: "2024-11-27",
        priority: "Medium",
        category: "Operations",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 8 for Aarav",
        description: "Description of Task 8",
        date: "2024-11-28",
        priority: "Low",
        category: "Content",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 6,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 3,
    firstName: "Vihaan",
    email: "employee3@example.com",
    password: "1234",
    tasks: [
      {
        title: "Task 1 for Vihaan",
        description: "Description of Task 1",
        date: "2024-11-21",
        priority: "Low",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2 for Vihaan",
        description: "Description of Task 2",
        date: "2024-11-22",
        priority: "Medium",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3 for Vihaan",
        description: "Description of Task 3",
        date: "2024-11-23",
        priority: "High",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4 for Vihaan",
        description: "Description of Task 4",
        date: "2024-11-24",
        priority: "Low",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5 for Vihaan",
        description: "Description of Task 5",
        date: "2024-11-25",
        priority: "Medium",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 6 for Vihaan",
        description: "Description of Task 6",
        date: "2024-11-26",
        priority: "High",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 7 for Vihaan",
        description: "Description of Task 7",
        date: "2024-11-27",
        priority: "Low",
        category: "Security",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 8 for Vihaan",
        description: "Description of Task 8",
        date: "2024-11-28",
        priority: "Medium",
        category: "Management",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 6,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    firstName: "Kabir",
    email: "employee4@example.com",
    password: "1234",
    tasks: [
      {
        title: "Task 1 for Kabir",
        description: "Description of Task 1",
        date: "2024-11-21",
        priority: "High",
        category: "UI",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2 for Kabir",
        description: "Description of Task 2",
        date: "2024-11-22",
        priority: "Low",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3 for Kabir",
        description: "Description of Task 3",
        date: "2024-11-23",
        priority: "Medium",
        category: "UI",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4 for Kabir",
        description: "Description of Task 4",
        date: "2024-11-24",
        priority: "High",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5 for Kabir",
        description: "Description of Task 5",
        date: "2024-11-25",
        priority: "Medium",
        category: "UI",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 6 for Kabir",
        description: "Description of Task 6",
        date: "2024-11-26",
        priority: "Low",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 7 for Kabir",
        description: "Description of Task 7",
        date: "2024-11-27",
        priority: "High",
        category: "UI",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 8 for Kabir",
        description: "Description of Task 8",
        date: "2024-11-28",
        priority: "Medium",
        category: "Content",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 6,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
];



const admin = {
  id: 1,
  firstName: "Rajesh",
  email: "admin@example.com",
  password: "1234",
};
export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
